### ISSUE TITLE
use env_var

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/ansible-saturn-l1#1]
Replace the need for init.sh by

- using /etc/environment - as per docs for localy run commands
- env_vars for ansible scripts
```
  vars:
    env_vars:
      SATURN_NETWORK: "{{ SATURN_NETWORK }}"
      FIL_WALLET_ADDRESS: "{{ FIL_WALLET_ADDRESS }}"
      NODE_OPERATOR_EMAIL: "{{ NODE_OPERATOR_EMAIL }}"
      #SATURN_NETWORK: "{{ lookup('ansible.builtin.env', 'SATURN_NETWORK', default='test') }}"
      #FIL_WALLET_ADDRESS: "{{ lookup('ansible.builtin.env', 'FIL_WALLET_ADDRESS', default=undefined) }}"
      #NODE_OPERATOR_EMAIL: "{{ lookup('ansible.builtin.env', 'NODE_OPERATOR_EMAIL', default=undefined) }}"
```
